# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Documentation
author: Bo Yuan
logo: ./docs/source/_static/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  exclude_patterns: [
    README,
    servers/*
  ]

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/boyuan99/neural-adjuster # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
